import { AchievementDefinition } from '@/src/types/achievements';

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'workouts_1',
    title: 'First Step',
    description: 'Complete your first workout.',
    category: 'workout',
    icon: 'fitness',
    color: '#FF6B35',
    points: 10,
    metric: 'totalWorkouts',
    threshold: 1,
  },
  {
    id: 'workouts_10',
    title: 'Getting Serious',
    description: 'Complete 10 workouts.',
    category: 'workout',
    icon: 'barbell',
    color: '#FF6B35',
    points: 25,
    metric: 'totalWorkouts',
    threshold: 10,
  },
  {
    id: 'streak_3',
    title: 'On a Roll',
    description: 'Maintain a 3-day workout streak.',
    category: 'consistency',
    icon: 'flame',
    color: '#FF6B35',
    points: 15,
    metric: 'streakDays',
    threshold: 3,
  },
  {
    id: 'streak_7',
    title: 'One-Week Streak',
    description: 'Maintain a 7-day workout streak.',
    category: 'consistency',
    icon: 'flame',
    color: '#FF6B35',
    points: 30,
    metric: 'streakDays',
    threshold: 7,
  },
  {
    id: 'streak_30',
    title: 'Monthly Machine',
    description: 'Maintain a 30-day workout streak.',
    category: 'consistency',
    icon: 'flame',
    color: '#FF6B35',
    points: 75,
    metric: 'streakDays',
    threshold: 30,
  },
  {
    id: 'weekly_3',
    title: '3 Days This Week',
    description: 'Work out on 3 different days in the last 7 days.',
    category: 'consistency',
    icon: 'calendar',
    color: '#00B894',
    points: 15,
    metric: 'workoutDaysLast7',
    threshold: 3,
  },
  {
    id: 'weekly_5',
    title: '5 Days This Week',
    description: 'Work out on 5 different days in the last 7 days.',
    category: 'consistency',
    icon: 'calendar',
    color: '#00B894',
    points: 30,
    metric: 'workoutDaysLast7',
    threshold: 5,
  },
  {
    id: 'weekly_7',
    title: 'Perfect Week',
    description: 'Work out every day for the last 7 days.',
    category: 'consistency',
    icon: 'calendar',
    color: '#00B894',
    points: 60,
    metric: 'workoutDaysLast7',
    threshold: 7,
  },
  {
    id: 'distance_5',
    title: 'On the Move',
    description: 'Reach 5 km total distance.',
    category: 'steps',
    icon: 'walk',
    color: '#2E86AB',
    points: 15,
    metric: 'totalDistanceKm',
    threshold: 5,
  },
  {
    id: 'long_distance_5',
    title: 'Long Haul',
    description: 'Complete an exercise of 5 km or more (last 90 days).',
    category: 'steps',
    icon: 'navigate',
    color: '#2E86AB',
    points: 20,
    metric: 'maxSingleDistanceKmLast90',
    threshold: 5,
  },
  {
    id: 'long_distance_10',
    title: 'Double Digits',
    description: 'Complete an exercise of 10 km or more (last 90 days).',
    category: 'steps',
    icon: 'navigate',
    color: '#2E86AB',
    points: 40,
    metric: 'maxSingleDistanceKmLast90',
    threshold: 10,
  },
  {
    id: 'duration_120',
    title: 'Two Hours In',
    description: 'Accumulate 120 minutes of activity.',
    category: 'consistency',
    icon: 'time',
    color: '#00B894',
    points: 20,
    metric: 'totalDurationMinutes',
    threshold: 120,
  },
  {
    id: 'sleep_streak_3',
    title: 'Rested',
    description: 'Sleep score ≥ 75 for 3 days in a row.',
    category: 'sleep',
    icon: 'moon',
    color: '#6C5CE7',
    points: 20,
    metric: 'sleepScoreStreak75',
    threshold: 3,
  },
  {
    id: 'sleep_streak_7',
    title: 'Sleep Champion',
    description: 'Sleep score ≥ 75 for 7 days in a row.',
    category: 'sleep',
    icon: 'moon',
    color: '#6C5CE7',
    points: 45,
    metric: 'sleepScoreStreak75',
    threshold: 7,
  },
  {
    id: 'zone45_30',
    title: 'Red Zone Rookie',
    description: 'Accumulate 30 minutes in HR zones 4–5 (last 30 days).',
    category: 'heart',
    icon: 'heart',
    color: '#E84393',
    points: 20,
    metric: 'hrZone45MinutesLast30',
    threshold: 30,
  },
  {
    id: 'zone45_120',
    title: 'Red Zone Regular',
    description: 'Accumulate 120 minutes in HR zones 4–5 (last 30 days).',
    category: 'heart',
    icon: 'heart',
    color: '#E84393',
    points: 50,
    metric: 'hrZone45MinutesLast30',
    threshold: 120,
  },
  {
    id: 'trainer_1',
    title: 'Trainer Session',
    description: 'Complete a fitness/circuit session (last 90 days).',
    category: 'variety',
    icon: 'people',
    color: '#0984E3',
    points: 15,
    metric: 'trainerSessionsLast90',
    threshold: 1,
  },
  {
    id: 'first_running',
    title: 'First Run',
    description: 'Complete your first running workout.',
    category: 'variety',
    icon: 'walk',
    color: '#00CEC9',
    points: 10,
    metric: 'sportCount',
    meta: { sport: 'RUNNING' },
    threshold: 1,
  },
  {
    id: 'first_cycling',
    title: 'First Ride',
    description: 'Complete your first cycling workout.',
    category: 'variety',
    icon: 'bicycle',
    color: '#00CEC9',
    points: 10,
    metric: 'sportCount',
    meta: { sport: 'CYCLING' },
    threshold: 1,
  },
  {
    id: 'first_swimming',
    title: 'First Swim',
    description: 'Complete your first swimming workout.',
    category: 'variety',
    icon: 'water',
    color: '#00CEC9',
    points: 10,
    metric: 'sportCount',
    meta: { sport: 'SWIMMING' },
    threshold: 1,
  },
  {
    id: 'xp_100',
    title: 'Leveling Up',
    description: 'Earn 100 XP.',
    category: 'rewards',
    icon: 'trophy',
    color: '#FDCB6E',
    points: 20,
    metric: 'xp',
    threshold: 100,
  },
];
