import { StyleSheet } from 'react-native';

export const WEB_DATE_INPUT_STYLE: Record<string, any> = {
  padding: 8,
  borderRadius: 8,
  borderWidth: 1,
  borderColor: '#D1D5DB',
  fontSize: 16,
};

export const instructorDashboardScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTopTitleWrap: {
    flex: 1,
    marginRight: 8,
  },
  headerWideRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    position: 'relative',
    minHeight: 60,
    paddingVertical: 2,
  },
  headerLeftControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexShrink: 0,
    zIndex: 1,
  },
  headerCenterOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 0,
  },
  headerRightControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
    flexShrink: 0,
    zIndex: 1,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D3436',
    textAlign: 'center',
  },
  headerTitleWideWeb: {
    lineHeight: 24,
  },
  selectButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
  },
  selectButtonActive: {
    backgroundColor: '#FF6B35',
  },
  selectButtonText: {
    color: '#636E72',
    fontWeight: '600',
  },
  selectButtonTextActive: {
    color: '#FFFFFF',
  },
  subtitle: {
    fontSize: 16,
    color: '#636E72',
    marginTop: 4,
    textAlign: 'center',
  },
  headerSubtitleWideWeb: {
    marginTop: 2,
    lineHeight: 20,
    marginBottom: 6,
  },
  settingsContentContainer: {
    paddingBottom: 12,
  },
  filterContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: 16,
    gap: 12,
  },
  filterContainerWideWeb: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    gap: 16,
  },
  rangeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  rangeRowWideWeb: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
    flexShrink: 1,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  actionsRowWideWeb: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
    flexShrink: 0,
  },
  filterLabel: {
    color: '#636E72',
    marginRight: 2,
  },
  filterLabelWeb: {
    fontSize: 11,
    marginTop: 15,
  },
  filterLabelMobile: {
    fontSize: 15,
    marginTop: 0,
  },
  rangeButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  rangeButtonsWideWeb: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexWrap: 'nowrap',
    gap: 8,
  },
  rangeButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
  },
  rangeButtonActive: {
    backgroundColor: '#2D3436',
  },
  rangeButtonText: {
    fontSize: 12,
    color: '#636E72',
    fontWeight: '600',
  },
  rangeButtonTextActive: {
    color: '#FFFFFF',
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 24,
    marginTop: 5,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 12,
    color: '#2D3436',
  },
  selectionInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    padding: 8,
    backgroundColor: '#FFF5F0',
    borderRadius: 8,
  },
  selectionText: {
    color: '#FF6B35',
    fontWeight: 'bold',
    marginRight: 8,
  },
  selectionHint: {
    color: '#FF6B35',
    fontSize: 12,
  },
  clearButtonText: {
    color: '#FF6B35',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  listContent: {
    padding: 16,
  },
  overviewContent: {
    padding: 16,
  },
  modeToggleRow: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 4,
    marginTop: 12,
  },
  modeToggleBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 10,
  },
  modeToggleBtnActive: {
    backgroundColor: '#FFFFFF',
  },
  modeToggleText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#636E72',
  },
  modeToggleTextActive: {
    color: '#FF6B35',
  },
  overviewHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    position: 'relative',
    zIndex: 50,
  },
  overviewTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2D3436',
  },
  autoFlagBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFF5F0',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  autoFlagBtnDisabled: {
    opacity: 0.6,
  },
  autoFlagWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    position: 'relative',
    zIndex: 60,
  },
  autoFlagIndicator: {
    marginLeft: 2,
  },
  autoFlagIndicatorHover: {
    position: 'relative',
    zIndex: 70,
  },
  autoFlagTooltip: {
    position: 'absolute',
    top: 22,
    right: -6,
    backgroundColor: '#2D3436',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    maxWidth: 240,
    zIndex: 9999,
  },
  autoFlagTooltipText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  autoFlagBtnText: {
    color: '#FF6B35',
    fontWeight: 'bold',
    fontSize: 12,
  },
  autoFlagCooldownText: {
    color: '#636E72',
    fontSize: 12,
    fontWeight: '700',
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  summaryCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  summaryLabel: {
    color: '#636E72',
    fontWeight: '600',
    fontSize: 12,
    marginBottom: 8,
  },
  summaryValue: {
    color: '#2D3436',
    fontSize: 20,
    fontWeight: 'bold',
  },
  flagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
    marginBottom: 6,
  },
  flagPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  flagPillText: {
    fontWeight: 'bold',
    fontSize: 12,
  },
  flagPillGood: {
    borderColor: '#00B894',
  },
  flagPillBad: {
    borderColor: '#D63031',
  },
  flagPillNone: {
    borderColor: '#636E72',
  },
  flagPillTextGood: {
    color: '#00B894',
  },
  flagPillTextBad: {
    color: '#D63031',
  },
  flagPillTextNone: {
    color: '#636E72',
  },
  syncInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    marginBottom: 12,
  },
  syncInfoText: {
    color: '#636E72',
    fontSize: 12,
    fontWeight: '600',
  },
  overviewLists: {
    gap: 12,
  },
  overviewListCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  listTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#2D3436',
    marginBottom: 12,
  },
  overviewListCardGood: {
    borderLeftWidth: 4,
    borderLeftColor: '#00B894',
  },
  overviewListCardBad: {
    borderLeftWidth: 4,
    borderLeftColor: '#D63031',
  },
  listTitleGood: {
    color: '#00B894',
  },
  listTitleBad: {
    color: '#D63031',
  },
  emptyListHint: {
    color: '#636E72',
    fontSize: 12,
    fontWeight: '600',
    paddingVertical: 6,
  },
  emptyListHintCenter: {
    color: '#636E72',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 10,
  },
  overviewCadetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  overviewCadetTextCol: {
    flex: 1,
    marginRight: 12,
    flexDirection: 'column',
    gap: 4,
  },
  overviewCadetNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  overviewCadetName: {
    color: '#2D3436',
    fontWeight: '600',
    flex: 1,
  },
  overviewCadetMeta: {
    color: '#636E72',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  overviewCadetMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  aiReasonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  aiFlagReasonText: {
    color: '#636E72',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    flexShrink: 1,
  },
  overviewCadetActions: {
    flexDirection: 'row',
    gap: 8,
  },
  flagActionBtn: {
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    padding: 8,
  },
  flagActionBtnActiveGood: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#00B894',
  },
  flagActionBtnActiveBad: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D63031',
  },
  overviewHint: {
    marginTop: 12,
    color: '#636E72',
    fontSize: 12,
    textAlign: 'center',
  },
  aiFlagBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 999,
    backgroundColor: '#F3F4F6',
  },
  aiFlagBadgeText: {
    color: '#636E72',
    fontWeight: '700',
    fontSize: 10,
  },
  emptyState: {
    padding: 40,
    alignItems: 'center',
  },
  emptyText: {
    color: '#636E72',
    fontSize: 16,
    marginBottom: 16,
  },
  emptyButton: {
    backgroundColor: '#FF6B35',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 24,
  },
  emptyButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    height: '80%',
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D3436',
  },
  modalDone: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FF6B35',
  },
  settingsModalHeader: {
    alignItems: 'center',
    marginBottom: 2,
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  settingsModalClose: {
    paddingVertical: 0,
    marginBottom: 0,
  },
  settingsModalContent: {
    paddingTop: 2,
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  modalItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalItemLeft: {
    flex: 1,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxSelected: {
    backgroundColor: '#FF6B35',
    borderColor: '#FF6B35',
  },
  modalItemText: {
    fontSize: 16,
    color: '#2D3436',
  },
  ldPill: {
    marginLeft: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: '#F3F4F6',
  },
  ldPillActive: {
    backgroundColor: '#2D3436',
  },
  ldPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#636E72',
  },
  ldPillTextActive: {
    color: '#FFFFFF',
  },
  iconButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#FFF5F0',
  },
  settingsContent: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2D3436',
    marginBottom: 16,
  },
  settingRow: {
    marginBottom: 24,
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#636E72',
    marginBottom: 12,
  },
  typeSelector: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 4,
  },
  typeOption: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 8,
  },
  typeOptionSelected: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  typeOptionText: {
    fontSize: 12,
    color: '#636E72',
    fontWeight: '500',
  },
  typeOptionTextSelected: {
    color: '#FF6B35',
    fontWeight: 'bold',
  },
  webModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  webModalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 12,
    width: '80%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  webDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  webDateLabel: {
    fontSize: 16,
    color: '#2D3436',
    fontWeight: '500',
  },
  webApplyButton: {
    backgroundColor: '#FF6B35',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
  },
  webApplyButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
